-- ===========================================
--   V6 : User pack inventory
--   Track how many unopened packs each user owns per template.
--   ON DELETE CASCADE: removing a template removes all inventory rows.
-- ===========================================

CREATE TABLE user_pack_inventory (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES ts_user(id),
    pack_template_id BIGINT NOT NULL REFERENCES pack_template(id) ON DELETE CASCADE,
    quantity         INT    NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    UNIQUE (user_id, pack_template_id)
);

CREATE INDEX idx_user_pack_inv_user ON user_pack_inventory (user_id);
