-- ===========================================
--   V10 : Production reset — wipe all data except users
--   Runs once via Flyway. All card images must be removed from disk separately.
-- ===========================================

-- Delete in FK-dependency order
DELETE FROM trade_session;
DELETE FROM user_pack_inventory;
DELETE FROM user_cards;
DELETE FROM live_feed_event;
DELETE FROM card;

-- Reset sequences so IDs start fresh from 1
ALTER SEQUENCE card_seq RESTART WITH 1;
ALTER SEQUENCE live_feed_event_seq RESTART WITH 1;

-- user_pack_inventory uses GENERATED BY DEFAULT AS IDENTITY — reset its internal sequence
ALTER TABLE user_pack_inventory ALTER COLUMN id RESTART WITH 1;
