spring.application.name=Backend_CardDropper

# Card images
app.card-images.dir=${CARD_IMAGES_DIR:./card-images}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

#Bdd
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/CardDropper}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#Logging

logging.level.root=${LOG_LEVEL:INFO}
#logging.pattern.console=%d{HH:mm:ss} %highlight(%-5level) [%logger{2}] %msg%n
logging.level.org.hibernate=WARN
logging.level.org.apache.camel=WARN

# Keycloak / OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:https://keycloak.andi27.synology.me/realms/carddropperts}

# CORS
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}



#doc openapi
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/v3/api-docs